Check-in 2: Components filled in
sebitommy123/Tic-Tac-Toe pull request #2
Opened 2021-09-27 00:38 UTC by misterluna

2021-09-27 07:00 UTC, sebitommy123 commented
@caelinsutch 
https://youtu.be/428BY2lSqcY?t=14
A video demonstrating the features

2021-09-27 18:47 UTC, caelinsutch requested changes
Left comments, fix issues and re-request review

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/App.tsx
> +function App() {
Prefer using `const`

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/App.tsx
> +  let [score, setScore]: [Score, any] = useState({ X: 0, O: 0 });
1. Use `const`
2. Variable names, lowercase `x` and `o`
3. When typing this, do this: 

```ts
const [score, setScore] = useState<Score>({ x: 0, o: 0});
```

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/App.tsx
> +  let [winner, setWinner]: [Winner, any] = useState(null);
See above

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/App.tsx
> +  function onGameOver(winner: Winner) {
Prefer arrow functions: 
```
const onGameOver = (winner: Winner) => {
...
}
```

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/App.tsx
> +    <div>
You don't have to use a `div` here, probably should be a `main` tbh but can also use `<>` as empty

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/App.tsx
> +      {winner ? <EndScreen winner={winner} playAgain={() => {setWinner(null)}} resetScore={() => {}}/> : <Game onGameOver={onGameOver}/>}
Is this done? Also space this out using line breaks, we'll talk more about this this week

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/colors.json
> +{
Prefer using a `constants` file instead of `json`

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/components/Board.tsx
> +export default function Board(props: Props) {
Prefer declaring function before export:

```
const Board: React.FC<Props> = (props) => {
// ...
}
```

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/components/EndScreen.tsx
> +export default function EndScreen(props: Props) {
See above

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/components/Game.tsx
> +  const [board, setBoard]: [Slot[][], any] = useState(
See comments on hooks in `App.tsx

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/components/Game.tsx
> +  const boardClickEvent = (x: number, y: number) => {
`handleBoardClick`

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/components/PersistantScore.tsx
> +      <span style={{ color: colors["X"] }}>{props.score.X}</span>
Lowercase

2021-09-27 18:47 UTC, caelinsutch commented on tic-tac-toe/src/utils.tsx
> +export function getSVG(symbol: Symbol): any {
Interesting way to approach this lol. I usually use an `Icon` component but this works too I guess

2021-09-29 02:27 UTC, caelinsutch reviewed
Very very nice. Left some style comments to make it cleaner.

Big thing would be using more files to decrease the length of some of these files.

When organizing components, I normally use modules.

i.e. For the Game Component, this would be the file structure
```
components
   Game
      Game.tsx 
      Game.utils.ts
      index.ts
```

In `index.ts` you'd put:
```
export { default } from './Game.tsx`
```

Utils would be all your util funcs exported as:
```
export { isBoardFull, ... }
```

2021-09-29 02:27 UTC, caelinsutch commented on tic-tac-toe/src/components/Board.tsx
> +const Board = (props: Props) => {
You can use shorthand here: `const Board = (props: Props) => ( ...`

2021-09-29 02:27 UTC, caelinsutch commented on tic-tac-toe/src/components/EndScreen.tsx
> +  if (props.winner !== "DRAW") {
This is very inefficient, will run this logic on each render. Do this inline in the rendering function rather than having this variable

2021-09-29 02:27 UTC, caelinsutch commented on tic-tac-toe/src/components/Game.tsx
> +const isBoardFull = (board: BoardType): Winner | null => {
Very nice util funcs

2021-09-29 02:27 UTC, caelinsutch commented on tic-tac-toe/src/components/Game.tsx
> +const Game = (props: Props) => {
Prefer destructuring props to make it cleaner:

```
const Game: React.FC<Props> = ({ onGameOver })
```

2021-09-29 02:27 UTC, caelinsutch commented on tic-tac-toe/src/components/PersistentScore.tsx
> +const PersistentScore = (props: Props) => {
Bad function name, this doesn't persist the score

2021-09-29 02:27 UTC, caelinsutch commented on tic-tac-toe/src/hooks/usePersistentData.tsx
> +function usePersistentObjectData<T>(
Clean, guessing you pulled this from somewhere, good use of google

2025-10-29 15:56 UTC, merged